// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0yNg_CHpIgGmMlAxoHQAe8AVT9VsNYGQ',
    appId: '1:267305482824:web:14479d9a9b56df2fc9b67d',
    messagingSenderId: '267305482824',
    projectId: 'app-inventario-e3d70',
    authDomain: 'app-inventario-e3d70.firebaseapp.com',
    storageBucket: 'app-inventario-e3d70.firebasestorage.app',
    measurementId: 'G-DM11KBF5TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNUETyOYbUoSQPLKzZxZNJ8FJ-AkiTAVQ',
    appId: '1:267305482824:android:c4411e970e81276ec9b67d',
    messagingSenderId: '267305482824',
    projectId: 'app-inventario-e3d70',
    storageBucket: 'app-inventario-e3d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgnUq81rJmpWC1G6GGKapitmYodO791jg',
    appId: '1:267305482824:ios:d96a28fa34eff696c9b67d',
    messagingSenderId: '267305482824',
    projectId: 'app-inventario-e3d70',
    storageBucket: 'app-inventario-e3d70.firebasestorage.app',
    iosBundleId: 'com.example.InVen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgnUq81rJmpWC1G6GGKapitmYodO791jg',
    appId: '1:267305482824:ios:d96a28fa34eff696c9b67d',
    messagingSenderId: '267305482824',
    projectId: 'app-inventario-e3d70',
    storageBucket: 'app-inventario-e3d70.firebasestorage.app',
    iosBundleId: 'com.example.InVen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0yNg_CHpIgGmMlAxoHQAe8AVT9VsNYGQ',
    appId: '1:267305482824:web:8332cb0301947359c9b67d',
    messagingSenderId: '267305482824',
    projectId: 'app-inventario-e3d70',
    authDomain: 'app-inventario-e3d70.firebaseapp.com',
    storageBucket: 'app-inventario-e3d70.firebasestorage.app',
    measurementId: 'G-5ZHQDHQTR2',
  );
}
